"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import InvestmentAgreementContent from "@/components/InvestmentAgreementContent";

const AgreementSkeleton = () => (
  <div className="min-h-screen bg-white text-black p-4 md:p-8 animate-pulse">
    <div className="max-w-[800px] mx-auto">
      {/* Centered actions bar skeleton */}
      <div className="flex justify-center items-center mb-8 bg-gray-50 h-16 rounded-lg border border-gray-100">
        <div className="bg-gray-200 h-10 w-44 rounded-lg"></div>
      </div>

      {/* Header skeleton */}
      <div className="flex flex-col items-center mb-8 border-b border-gray-200 pb-6">
        <div className="bg-gray-300 h-8 w-64 rounded mb-2"></div>
        <div className="bg-gray-200 h-4 w-32 rounded"></div>
      </div>

      {/* Document Content Skeleton */}
      <div className="space-y-6">
        <div className="space-y-2">
          <div className="bg-gray-300 h-6 w-1/4 rounded"></div>
          <div className="bg-gray-200 h-4 w-full rounded"></div>
          <div className="bg-gray-200 h-4 w-5/6 rounded"></div>
        </div>

        <div className="space-y-2 pt-4">
          <div className="bg-gray-300 h-6 w-1/3 rounded"></div>
          <div className="bg-gray-200 h-4 w-full rounded"></div>
          <div className="bg-gray-200 h-4 w-full rounded"></div>
          <div className="bg-gray-200 h-4 w-2/3 rounded"></div>
        </div>

        <div className="space-y-2 pt-4">
          <div className="bg-gray-300 h-6 w-1/5 rounded"></div>
          <div className="bg-gray-200 h-4 w-full rounded"></div>
          <div className="bg-gray-200 h-4 w-3/4 rounded"></div>
        </div>

        {/* Signatures skeleton */}
        <div className="grid grid-cols-2 gap-8 pt-12 mt-12 border-t border-gray-200">
          <div className="space-y-2">
            <div className="bg-gray-200 h-4 w-24 rounded"></div>
            <div className="bg-gray-300 h-16 w-full rounded-lg"></div>
            <div className="bg-gray-200 h-4 w-32 rounded"></div>
          </div>
          <div className="space-y-2">
            <div className="bg-gray-200 h-4 w-28 rounded"></div>
            <div className="bg-gray-300 h-16 w-full rounded-lg"></div>
            <div className="bg-gray-200 h-4 w-36 rounded"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
);

export default function InvestmentAgreementPage() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem("investorToken");
    if (!token) {
      router.push("/invest");
      return;
    }

    const fetchData = async () => {
      try {
        const res = await fetch("/api/invest/data", {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (res.status === 401) {
          localStorage.removeItem("investorToken");
          router.push("/invest");
          return;
        }
        if (!res.ok) throw new Error("Failed to fetch data");
        const jsonData = await res.json();
        setData(jsonData);
      } catch (err) {
        setError("Failed to load agreement data");
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [router]);

  if (loading) return <AgreementSkeleton />;
  if (error) return <div className="p-8 text-center text-red-600">{error}</div>;
  if (!data) return null;

  const { investor } = data;

  return (
    <div className="min-h-screen bg-white text-black p-4 md:p-8">
      <div className="max-w-[800px] mx-auto">
        {/* Actions Bar - Hidden when printing */}
        <div className="flex justify-center items-center mb-8 print:hidden bg-gray-50 p-4 rounded-lg border border-gray-100">
          <button
            onClick={() => window.print()}
            className="bg-black text-white px-6 py-2 rounded-lg font-semibold hover:bg-gray-800 transition-colors"
          >
            Print / Save as PDF
          </button>
        </div>

        {/* Printable Area */}
        <div className="print:w-full">
          <div className="text-center mb-8 border-b border-gray-200 pb-4">
            <h1 className="text-2xl font-bold uppercase tracking-wide">
              Investment Agreement
            </h1>
            <p className="text-gray-500 text-sm mt-1">Official Document</p>
          </div>

          <InvestmentAgreementContent
            investorName={investor.name}
            amount={investor.initialAmount}
            startDate={investor.startDate}
          />

          <div className="mt-12 pt-4 border-t border-gray-100 text-center text-xs text-gray-400 print:block hidden">
            <p>Generated by Yuvara Investment Platform</p>
            <p>{new Date().toLocaleString()}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
