"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import InvestmentAgreementContent from "@/components/InvestmentAgreementContent";
import YuvaraLoader from "@/components/YuvaraLoader";

export default function InvestmentAgreementPage() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem("investorToken");
    if (!token) {
      router.push("/invest");
      return;
    }

    const fetchData = async () => {
      try {
        const res = await fetch("/api/invest/data", {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (res.status === 401) {
          localStorage.removeItem("investorToken");
          router.push("/invest");
          return;
        }
        if (!res.ok) throw new Error("Failed to fetch data");
        const jsonData = await res.json();
        setData(jsonData);
      } catch (err) {
        setError("Failed to load agreement data");
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [router]);

  if (loading)
    return (
      <div className="flex items-center justify-center min-h-screen">
        <YuvaraLoader text="Loading Agreement..." />
      </div>
    );
  if (error) return <div className="p-8 text-center text-red-600">{error}</div>;
  if (!data) return null;

  const { investor } = data;

  return (
    <div className="min-h-screen bg-white text-black p-4 md:p-8">
      <div className="max-w-[800px] mx-auto">
        {/* Actions Bar - Hidden when printing */}
        <div className="flex justify-between items-center mb-8 print:hidden bg-gray-50 p-4 rounded-lg border border-gray-100">
          <button
            onClick={() => window.close()}
            className="text-gray-600 hover:text-gray-900 font-medium text-sm"
          >
            ← Close Window
          </button>
          <button
            onClick={() => window.print()}
            className="bg-black text-white px-6 py-2 rounded-lg font-semibold hover:bg-gray-800 transition-colors"
          >
            Print / Save as PDF
          </button>
        </div>

        {/* Printable Area */}
        <div className="print:w-full">
          <div className="text-center mb-8 border-b border-gray-200 pb-4">
            <h1 className="text-2xl font-bold uppercase tracking-wide">
              Investment Agreement
            </h1>
            <p className="text-gray-500 text-sm mt-1">Official Document</p>
          </div>

          <InvestmentAgreementContent
            investorName={investor.name}
            amount={investor.initialAmount}
            startDate={investor.startDate}
          />

          <div className="mt-12 pt-4 border-t border-gray-100 text-center text-xs text-gray-400 print:block hidden">
            <p>Generated by Yuvara Investment Platform</p>
            <p>{new Date().toLocaleString()}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
