export const PRODUCT_CATEGORIES = [
  "Women's Fashion",
  "Men's Fashion",
  "Phones & Telecommunications",
  "Computer, Office & Security",
  "Consumer Electronics",
  "Jewelry & Watches",
  "Home, Pet & Appliances",
  "Bags & Shoes",
  "Toys, Kids & Babies",
  "Outdoor Fun & Sports",
  "Beauty, Health & Hair",
  "Automobiles & Motorcycles",
  "Tools & Home Improvement",
  "Furniture",
  "Food",
  "Books",
  "Other",
];
